### ISSUE TITLE
Mismapped Parameters When Pulling Categories from Budget Detail

### ISSUE THREAD

**Issue by birdwing** [andreroggeri/ynab-sdk-python#102]
If a category is access directly it works fine, however when pulling the categories from the Budget Detail endpoint the category.goal_type is mapped to the 'Note' endpoint.

In file
**Iynab_sdk/api/models/responses/budget_detail.py**

Lines: 87 - 89
```
       goal_type = parsers.from_union(
            [parsers.from_str, parsers.from_none], obj.get("note")
        )
```

**Comment by andreroggeri** [comment]
Closed by #103
