### ISSUE TITLE
Esse projeto continua ativamente sendo mantido? 👀

### ISSUE THREAD

**Issue by felipython-routable** [andreroggeri/ynab-sdk-python#123]
Oi, tô considerando sair da minha implementação própria para me comunicar com a API do YNAB, mas para tomar essa decisão gostaria de saber se este projeto ainda está sendo mantido. @andreroggeri pode me responder essa? Se não eu poderia ajudar na manutenção também.

**Comment by andreroggeri** [comment]
Fala @felipython-routable (ou @lipemorais 👀) 

Eu não tenho contribuído ativamente para o projeto pq não tive nenhuma outra necessidade, uso ele para um propósito bem similar a você (Sincronizar os meus bancos com o YNAB).

Novas contribuições são bem vindas e se for o caso também posso te adicionar aqui no repo pra ajudar 😄

**Comment by lipemorais** [comment]
Comentei com o Github da firma por acidente. Vou ver de fazer essa migração no meu projeto. Conforme for vendo melhorias eu vou abrindo os PRs e fazendo as sugestões. 

Uma sugestão que penso é atualizar o README nessa parte do Warning.
![image](https://user-images.githubusercontent.com/5021565/223462452-578ea319-799c-4c56-9798-6c081116ec42.png)

Essa mensagem me fez não utilizar este projeto por medo de acabar tendo que refazer tudo de novo.

**Comment by andreroggeri** [comment]
Eu imaginei mesmo hehe

Mas boa observação, acabei esquecendo esse warning.

Vou remover pq na minha perspectiva isso já está bem estável
