### ISSUE TITLE
Running Balance

### ISSUE THREAD

**Issue by Ga68** [andreroggeri/ynab-sdk-python#138]
It looks like Running Balance (available in the UI) isn't something that's in this API, likely because it seems not to be in the API spec.

¿Is that right?

Presuming so, then would the "right" way to do it be to grab the current account balance and then self-calculate it by going backwards in time using the transaction dates.

**Comment by andreroggeri** [comment]
Yeah, I glanced at the spec and couldn't find this field available in the API.

You could calculate this by looping through all transactions for the beginning and calculating the current balance manually.
