### ISSUE TITLE
Add black as a code formatter

### ISSUE THREAD

**Issue by Tommaso-n** [andreroggeri/ynab-sdk-python#70]
I suggest to use black as a code formatter.
This repo should be what we need:
https://github.com/jpetrucciani/black-check

**Comment by andreroggeri** [comment]
Is it possible to use black formatter with single quotes ? (It's my preference)

**Comment by Tommaso-n** [comment]
You can use --skip-string-normalization option to avoid converting single quotes to double quotes

**Comment by andreroggeri** [comment]
Ok, I'm still undecided about single/double quotes, but I agree that black can be a good addition to this project.


I have zero knowledge abou github actions, can we mix them with travis ?

Also, do you want to tackle this one ?

And last but not least, add the black badge on the readme 🏴

**Comment by Tommaso-n** [comment]
We can use pre-commit. I've found this guide:

https://www.mattlayman.com/blog/2018/python-code-black/

You have to add pre-commit to requirements-dev.txt, create the file .pre-commit-config.yaml in your repo and add to this file the following:

repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7

This way black will check and modify every code before being committed.
Although i  don't know if it can be used with the --skip-string-normalization option

**Comment by andreroggeri** [comment]
The pre-commit could be an extra, but since it can be skipped, its important to run the check on the CI.

It seems to be easy to do this in the lint step (That currently does nothing 😆 )

**Comment by Tommaso-n** [comment]
ok, so you just have to add "black --check ." to the lint step?

**Comment by andreroggeri** [comment]
Yep


- Add black check command for the lint step
- The build is now broken
- Run black format command and commit all changes
- The build is green again
- Add black badge to the README 😁

Em seg, 10 de ago de 2020 19:59, Tommaso-n <notifications@github.com>
escreveu:

**Comment by andreroggeri** [comment]
Done by #71
